project_name: watcher

version: 2

before: 
  hooks:
  - sudo apt update
  - sudo apt install -y clang llvm gcc-multilib iproute2 bpfcc-tools linux-headers-$(uname -r) 
  - make generate

builds:
  - main: ./
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

